version: "3.9"

services:
  calibre-web:
    image: zkhan93/calibre-web:latest
    ports:
      - 8083:8083
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.khancave-calibre.rule=Host(`${CALIBRE_DOMAIN}`)
      - traefik.http.routers.khancave-calibre.tls=true
      - traefik.http.routers.khancave-calibre.tls.certresolver=le
    environment:
      - CALIBRE_DBPATH=/data
    volumes:
      - ${CALIBRE_WEB_DATA_DIR}:/data
      - ${CALIBRE_LIBRARY_DIR}:/library
      - ${CALIBRE_IMPORT}:/import
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.7:3100/loki/api/v1/push"

  aria2:
    image: zkhan93/aria2-daemon:latest
    ports:
      - 6800:6800
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.khancave-aria.rule=Host(`${ARIA2_DOMAIN}`) && Path(`/jsonrpc`)
      - traefik.http.routers.khancave-aria.tls.certresolver=le
    volumes:
      - aria2:/downloads
    environment:
      SECRET: ${ARIA2_RPC_SECRET}
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.7:3100/loki/api/v1/push"

  aria-web:
    image: zkhan93/aria2-webui:latest      
    ports:
      - 80
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.khancave-aria-web.rule=Host(`${ARIA2_DOMAIN}`)
      - traefik.http.routers.khancave-aria-web.tls.certresolver=le
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.7:3100/loki/api/v1/push"

  db:
    image: postgres
    ports:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Kolkata
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${NEXTCLOUD_DB}
      - POSTGRES_USER=${NEXTCLOUD_USER}
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.7:3100/loki/api/v1/push"

  nextcloud:
    build: ./nextcloud 
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.khancave-nextcloud.rule=Host(`${NEXTCLOUD_DOMAIN}`)
      - traefik.http.routers.khancave-nextcloud.tls.certresolver=le
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${NEXTCLOUD_DB}
      - POSTGRES_USER=${NEXTCLOUD_USER}
      - POSTGRES_HOST=db
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost 127.0.0.1 ${NEXTCLOUD_DOMAIN}
      - OVERWRITEPROTOCOL=https
      - REDIS_HOST=redis
    volumes:
      - nextcloud:/var/www/html
      - ${NEXTCLOUD_USERS_DRIVE}/common:/drive/common
      - ${NEXTCLOUD_USERS_DRIVE}/bushra:/drive/bushra
      - ${NEXTCLOUD_USERS_DRIVE}/zeeshan:/drive/zeeshan
      - ${NEXTCLOUD_USERS_DRIVE}/aalishan:/drive/aalishan
      - ${NEXTCLOUD_USERS_DRIVE}/sarfaraz:/drive/sarfaraz
    depends_on:
      - db
      - redis
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.7:3100/loki/api/v1/push"

  redis:
    image: redis:alpine
    restart: always
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.7:3100/loki/api/v1/push"

volumes:
  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${DB_DATA_DIR}
  nextcloud:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${NEXTCLOUD_DIR}
  aria2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${ARIA2_DOWNLOADS}

networks:
  default:
    external: true
    name: traefik_proxy
