version: "3"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:4.0.5-nightly
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.entertainment-radarr.rule=Host(`${RADARR_DOMAIN}`)
      - traefik.http.routers.entertainment-radarr.tls.certresolver=le
      - traefik.http.routers.entertainment-radarr.middlewares=simple-auth
    environment:
      - TZ=Asia/Kolkata
      - PUID=0
      - GUID=0
    volumes:
      - ${RADARR_DATA_DIR}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.7:3100/loki/api/v1/push"

  sonarr:
    image: lscr.io/linuxserver/sonarr
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.entertainment-sonarr.rule=Host(`${SONARR_DOMAIN}`)
      - traefik.http.routers.entertainment-sonarr.tls.certresolver=le
      - traefik.http.routers.entertainment-sonarr.middlewares=simple-auth
    environment:
      - TZ=Asia/Kolkata
      - PUID=0
      - GUID=0
    volumes:
      - ${SONARR_DATA_DIR}:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.7:3100/loki/api/v1/push"


  jackett:
    image: lscr.io/linuxserver/jackett
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.entertainment-jackett.rule=Host(`${JACKETT_DOMAIN}`)
      - traefik.http.routers.entertainment-jackett.tls.certresolver=le
      - traefik.http.routers.entertainment-jackett.middlewares=simple-auth
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ${JACKETT_DATA}/config:/config
      - ${JACKETT_DATA}/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.7:3100/loki/api/v1/push"

  plex:
    image: lscr.io/linuxserver/plex
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:-true}
      - traefik.http.routers.entertainment-plex.rule=Host(`${PLEX_DOMAIN}`)
      - traefik.http.routers.entertainment-plex.tls.certresolver=le
      - traefik.http.services.entertainment-plex.loadbalancer.server.port=32400
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
#      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}
      - ADVERTISE_IP=${PLEX_DOMAIN}
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ${PLEX_CONFIG}:/config
      - ${PLEX_TV}:/data/tvshows
      - ${PLEX_MOVIES}:/data/movies
      - ${PLEX_CCTV}:/data/cctv
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "http://192.168.1.7:3100/loki/api/v1/push"

networks:
  default:
    external: true
    name: traefik_proxy
